id: P31DC8631
initial_creation_type: input
source_metadata:
  title: Wealth and Prosperity Series
  language: en
  description: 'A selection of texts on the theme of wealth and prosperity including
    rites for summoning the spirit of prosperity or abundance (g.yang ''gugs):'
  volume:
    b4844ba7b79a4d5b82c3c8457c7ae503:
      title: Sang Offering to Yellow Jambhala
      parent: Offering
    180f60b6c0d046a3823f278640483ccc:
      title: Great Clouds of First-Portion Offerings for Prosperity
      parent: Offering
    3f84c3786a1e43e29f3ddc910544be1d:
      title: 'Summoning the Spirit of Abundance: A Rain of Flowers'
      parent: Summoning Prosperity
    66d64f80200d41619ffc401a838da2aa:
      title: 'The Summoning Hook of Wish-Fulfilment: An Appeal for Prosperity'
      parent: Summoning Prosperity
    820ee91cfd9f4d829aa6ccaa73ae91bc:
      title: Summoning Prosperity
      parent: Summoning Prosperity
    8196f87b72084b98bf7a84aedbb7b893:
      title: A Brief Prayer for Summoning Prosperity
      parent: Summoning Prosperity
    d3c174bf61f743aea6a1c8086bc151de:
      title: Summoning the Spirit of Abundance - The Hook of Divine Substance
      parent: Summoning Prosperity
    4d2711eb90944d3e88865a103ce9a6b5:
      title: An Appeal for the Prosperity of Teaching and Studying the Five Major
        Scriptures
      parent: Summoning Prosperity
created_at: '2022-03-01T06:34:53.424920'
last_modified_at: '2022-03-01T06:34:53.424926'
